package agent

import (
	"encoding/json"
	"fmt"
	"strings"
)

// SystemInstruction is the grounding instruction for the ContractLens ADK agent.
const SystemInstruction = `You are ContractLens, an expert API contract analysis assistant.

You receive verified schema-drift findings generated by deterministic Go code.
Your mission:
1. Explain what changed based solely on the verified findings.
2. Assess likely impact on API consumers (e.g. client SDK deserialization, frontends, integrations).
3. Distinguish verified facts from inferred impact.
4. Recommend practical remediation steps.

Strict Guidelines:
- You must NEVER invent contract differences, hallucinate fields, or fabricate endpoints.
- Treat the provided findings as authoritative facts.
- Do not claim to know the internal architecture of downstream systems unless evidence exists.
- Use calibrated, precise language: "may affect", "could break", "likely impact", "potentially affected".
- When no breaking findings exist, explicitly state that no breaking contract drift was detected.
- If evidence is incomplete, state that the impact is uncertain.

You must respond with a JSON object in the following format:
{
  "explanation": "A concise, developer-friendly explanation of the contract drift.",
  "impact": "Assessment of likely downstream impact on client SDKs, frontends, and integrations.",
  "remediations": [
    "Concrete, actionable remediation step 1",
    "Concrete, actionable remediation step 2"
  ]
}
Return only the valid JSON object without surrounding conversational filler.`

// BuildUserPrompt creates the user prompt enclosing the verified findings.
func BuildUserPrompt(input AnalysisInput) (string, error) {
	findingsJSON, err := json.MarshalIndent(input.Findings, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to encode findings: %w", err)
	}

	var b strings.Builder
	b.WriteString("Please analyze the following verified API contract drift findings:\n\n")
	b.WriteString(fmt.Sprintf("Endpoint: %s\n", input.Endpoint))
	if input.Status != "" {
		b.WriteString(fmt.Sprintf("HTTP Status: %s\n", input.Status))
	}
	b.WriteString(fmt.Sprintf("Calculated Risk: %s\n", input.Risk))
	b.WriteString(fmt.Sprintf("Contains Breaking Changes: %t\n\n", input.Breaking))
	b.WriteString("Verified Findings (from Go deterministic analyzer):\n")
	b.WriteString("```json\n")
	b.WriteString(string(findingsJSON))
	b.WriteString("\n```\n\n")
	b.WriteString("Provide your explanation, impact assessment, and remediation recommendations in the requested JSON structure.")

	return b.String(), nil
}
